apiVersion: v1
kind: Service
metadata:
  name: demo-headless
  # publishNotReadyAddresses: True
  # Use the DNS lookup mechanism to find even those unready pods. To tell Kubernetes you want all pods added to a service, regardless of the pod’s readiness status,
  # you must add the following annotation to the service:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  # This makes the service Headless. K8 won't assign it a clusterIP though which clients could connect to the pods backing it.
  clusterIP: None
  selector:
    app: demo
    enabled: "true"
  ports:
  - port: 80
    targetPort: 8080
