apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    # creation_method: manual
    # env: prod
    enabled: "true"
    app: demo
spec:
  containers:
  - name: kubia
    image: luksa/kubia
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
