apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    # defining the PV's size
    storage: 1Gi
  # It can neither be mounted by a single client for reading and writing or by multiple clients for reading only
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  # After the claim is released (for example the pvc that binds to the pv is deleted), the PersistentVolume should be retained (not erased or deleted).
  # If PVC is deleted, on this setting the pv will show status of RELEASED, not AVAILABLE. Because the data left by the previous pod using the pvc is still there, and
  # a new pod using the same PV could read the data left there, even if the claim and pod were in a different namespace.
  # Retain, Recycle, Delete
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    # Name of the PersistentDisk, as can be seen if created with Terraform (the name you gave it), or can look up in GCP console under compute/disks.
    # Backed by GCE PersistentDisk you created.
    pdName: mongodb
    fsType: ext4
