apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: demo
    name: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo
    volumeMounts:
      - name: mongodb-data
        # Directory path location to mount in container
        mountPath: /data/db
    # resources:
    #   limits:
    #     memory: "64Mi"
    #     cpu: "250m"
    ports:
      - containerPort: 27017
        protocol: TCP
  volumes:
    - name: mongodb-data
      # directory location on host
      hostPath:
        path: /data/db
